Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace mvc4.Models;
public class Customer{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id{ get; set; }
    public string? Name{ get; set; }
    public int Orders{ get; set; }
}

Models/ErrorViewModel.cs
namespace mvc4.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CustomerController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc4.Models;
using mvc4.Data;

namespace mvc4.Controllers;

public class CustomerController : Controller
{
    CustomerDbContext cdb=new CustomerDbContext();
    public IActionResult Index()
    {
       return View();
    }
    public IActionResult Create(){
        return View();

    }
    public IActionResult Updatedetails(){
        return View();
    }
    public IActionResult Add_Details(Customer c){
        
        cdb.Customers.Add(c);
        cdb.SaveChanges();
        return RedirectToAction("Index");
    }
    public IActionResult Retrieve(){
        var res=cdb.Customers.ToList();
        return View(res);
    }
    
    public IActionResult Edit(Customer c){
        Customer res=cdb.Customers.Find(c.Id);
        if(res==null){
            return Content("<center><u><h1>Id Not Found</h1></u></center>","text/html");
        }
        res.Orders=c.Orders;
        cdb.SaveChanges();
        return RedirectToAction("Retrieve");
    }
    public IActionResult Delete(){
        return View();
    }
    public IActionResult Delete_Details(Customer c){
        Customer res=cdb.Customers.Find(c.Id);
        if(res!=null){
            cdb.Remove(res);
            cdb.SaveChanges();
            return RedirectToAction("Retrieve");
        }
        return Content("<center><u><h1>Id Not Found</h1></u></center>","text/html");
        
    }

} 

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc4.Models;

namespace mvc4.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Customer/Create.cshtml
@model mvc4.Models.Customer

@using(Html.BeginForm("Add_Details","Customer")){
    @* <p>Customer Id : @Html.TextBoxFor(x=>x.Id)</p> *@
    <p>Customer Id : @Html.TextBoxFor(x=>x.Id)</p>
    <p>Customer Name : @Html.TextBoxFor(x=>x.Name)</p>
    <p>Customer Order : @Html.TextBoxFor(x=>x.Orders)</p>
   <input type="submit" value="submit">
}

Views/Customer/Delete.cshtml
@model mvc4.Models.Customer
@using(Html.BeginForm("Delete_Details","Customer")){
    <p>Enter Customer Id to Delete : @Html.TextBoxFor(x=>x.Id)</p> 
   <input type="submit">
}

Views/Customer/Index.cshtml
<center>
    <h1><u>Perform the required CRUD Operation</u></h3><br>
    <h3>@Html.ActionLink("Add Data","Create")</h3><br>
    <h3>@Html.ActionLink("Retrieve Data","Retrieve")</h3><br>
    <h3>@Html.ActionLink("Update Data","Updatedetails")</h3><br>
    <h3>@Html.ActionLink("Delete Data","Delete")</h3><br>
</center>

Views/Customer/Retrieve.cshtml
<style>
    center{
        border-color: brown;
        border-radius: 8px;
    }
    table {
        width: 100%; 
        border-collapse: collapse; 
        color:brown;    
    }
    th, td {
        padding: 10px; 
        border: 2px solid black;
    }
    h1{
        color: brown;
    }
</style>
<center>
    <h1><u>Details Of All Customers</u></h1><br>
    <table>
        <tr>
            <th>Customer_Id</th>
            <th>Customer_Name</th>
            <th>Customer_Orders</th>
        </tr>
            @foreach(var i in Model){
                <tr>
                    <td>@i.Id</td>
                    <td>@i.Name</td>
                    <td>@i.Orders</td>
                </tr>
            }
    </table>
</center>

Views/Customer/Updatedetails.cshtml
@model mvc4.Models.Customer
@using(Html.BeginForm("Edit","Customer")){
    <p>Enter Customer Id : @Html.TextBoxFor(x=>x.Id)</p>
    @* <p>Update Customer Name : @Html.TextBoxFor(x=>x.Name)</p> *@
    <p>Update Customer Orders : @Html.TextBoxFor(x=>x.Orders)</p>
   <input type="submit">
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvc4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>